#!/bin/sh

request_data="{\"consumer_key\": \"$POCKET_CONSUMER_KEY\", \"access_token\": \"$POCKET_ACCESS_TOKEN\", \"detailType\":\"complete\"}"
while (("$#" >= 2)); do
  param=$1
  value=$2
  request_data=$(jq --arg param $param --arg value $value '. + {($param): $value}' <<<"$request_data")
  shift 2
done

curl -sL https://getpocket.com/v3/get --insecure -X POST -H "Content-Type: application/json" -H "X-Accept: application/json" -d @- <<<$request_data
