#!/bin/sh

request_data="{\"consumer_key\": \"$POCKET_CONSUMER_KEY\", \"access_token\": \"$POCKET_ACCESS_TOKEN\", \"count\":1}"

curl -isL https://getpocket.com/v3/get --insecure -X POST \
-H "Content-Type: application/json" -H "X-Accept: application/json" -d @- <<<$request_data | grep '^x-limit'
